### ISSUE TITLE
Optional to hide preview button for certain documents

### ISSUE THREAD

**Issue by jduijm** [kaliberjs/sanity-plugin-preview#2]
Soms heb je een document die puur informatief is, die geen route heeft en geen frontend. De preview button is er dan nog steeds. Als je daarom klikt krijg je een error

**Comment by EECOLOR** [comment]
De code om die conditie mee te nemen zit in het project zelf: https://github.com/kaliberjs/sanity-plugin-preview#adding-the-custom-document-actions

Je kunt dit dus nu al doen in het bestand `resolveDocumentActions.js`
